[package]
authors = ["bus710"]
edition = "2021"
name = "turtlebot2-examples"
version = "0.1.0"

[dependencies]
anyhow = "1.0.52"
itertools = "0.10.3"
serialport = "4.0.1"

[dependencies.turtlebot2]
package = "turtlebot2"
path = "../../"

